/**
 * Mã hành động của nhật ký thao tác (`AuditLog.hanhDong`) — NGUỒN DUY NHẤT.
 *
 * Mỗi mã bằng đúng tên khoá của nó (lưới test ép). Phase sau bổ sung mã của mình VÀO ĐÂY, không khai
 * chuỗi rời ở nơi gọi.
 */
export const HANH_DONG = {
  DANG_NHAP_OK: "DANG_NHAP_OK",
  DANG_NHAP_SAI: "DANG_NHAP_SAI",
  DANG_NHAP_BI_KHOA: "DANG_NHAP_BI_KHOA",
  DANG_XUAT: "DANG_XUAT",
  DOI_MAT_KHAU: "DOI_MAT_KHAU",
  DOI_MAT_KHAU_LAN_DAU: "DOI_MAT_KHAU_LAN_DAU",
  TU_CHOI_QUYEN: "TU_CHOI_QUYEN",
  TAI_KHOAN_TAO: "TAI_KHOAN_TAO",
  TAI_KHOAN_SUA_QUYEN: "TAI_KHOAN_SUA_QUYEN",
  TAI_KHOAN_KHOA: "TAI_KHOAN_KHOA",
  TAI_KHOAN_MO_KHOA: "TAI_KHOAN_MO_KHOA",
  TAI_KHOAN_DAT_LAI_MK: "TAI_KHOAN_DAT_LAI_MK",
  TAI_KHOAN_XOA: "TAI_KHOAN_XOA",
  // Cài đặt, dữ liệu, đồng bộ, giá vốn, quảng cáo.
  DU_LIEU_XOA_TOAN_BO: "DU_LIEU_XOA_TOAN_BO",
  DU_LIEU_DUNG_LAI_TU_KHO: "DU_LIEU_DUNG_LAI_TU_KHO",
  CAI_DAT_KENH: "CAI_DAT_KENH",
  CAI_DAT_TINH_LAI_PHI: "CAI_DAT_TINH_LAI_PHI",
  DANH_MUC_CHI_PHI_TAO: "DANH_MUC_CHI_PHI_TAO",
  DANH_MUC_CHI_PHI_SUA: "DANH_MUC_CHI_PHI_SUA",
  DANH_MUC_CHI_PHI_AN_HIEN: "DANH_MUC_CHI_PHI_AN_HIEN",
  DANH_MUC_CHI_PHI_XOA: "DANH_MUC_CHI_PHI_XOA",
  CAI_DAT_NGUONG_TON: "CAI_DAT_NGUONG_TON",
  CAI_DAT_THONG_TIN_SHOP: "CAI_DAT_THONG_TIN_SHOP",
  KHOA_KET_NOI_LUU: "KHOA_KET_NOI_LUU",
  KHOA_KET_NOI_THAY_META: "KHOA_KET_NOI_THAY_META",
  N8N_LUU_KET_NOI: "N8N_LUU_KET_NOI",
  N8N_CAI_WORKFLOWS: "N8N_CAI_WORKFLOWS",
  DONG_BO_KICH_HOAT: "DONG_BO_KICH_HOAT",
  NGUONG_TON_SUA: "NGUONG_TON_SUA",
  GIA_VON_SUA: "GIA_VON_SUA",
  GIA_VON_IMPORT: "GIA_VON_IMPORT",
  GIA_VON_AP_THEO_PANCAKE: "GIA_VON_AP_THEO_PANCAKE",
  ADS_IMPORT: "ADS_IMPORT",
  // Tiền: dòng tiền, sổ quỹ, khoản vay, tiết kiệm, chi phí, thùng rác.
  DONG_TIEN_TAO: "DONG_TIEN_TAO",
  DONG_TIEN_SUA: "DONG_TIEN_SUA",
  DONG_TIEN_XOA: "DONG_TIEN_XOA",
  CHOT_SO_DU_LUU: "CHOT_SO_DU_LUU",
  CHOT_SO_DU_XOA: "CHOT_SO_DU_XOA",
  VI_SHOPEE_IMPORT: "VI_SHOPEE_IMPORT",
  QUY_TOI_THIEU_DAT: "QUY_TOI_THIEU_DAT",
  VAY_TAO: "VAY_TAO",
  VAY_SUA: "VAY_SUA",
  VAY_XOA: "VAY_XOA",
  VAY_TAT_TOAN: "VAY_TAT_TOAN",
  VAY_GHI_KY: "VAY_GHI_KY",
  THAU_CHI_TAT_TOAN: "THAU_CHI_TAT_TOAN",
  TIET_KIEM_TAO: "TIET_KIEM_TAO",
  TIET_KIEM_SUA: "TIET_KIEM_SUA",
  TIET_KIEM_XOA: "TIET_KIEM_XOA",
  TIET_KIEM_TAT_TOAN: "TIET_KIEM_TAT_TOAN",
  TIET_KIEM_MO_LAI: "TIET_KIEM_MO_LAI",
  CHI_PHI_TAO: "CHI_PHI_TAO",
  CHI_PHI_SUA: "CHI_PHI_SUA",
  CHI_PHI_XOA: "CHI_PHI_XOA",
  CHI_PHI_BAT_DINH_KY: "CHI_PHI_BAT_DINH_KY",
  CHI_PHI_DUNG_DINH_KY: "CHI_PHI_DUNG_DINH_KY",
  NHAP_HANG_GHI_CHI_PHI: "NHAP_HANG_GHI_CHI_PHI",
  THUNG_RAC_KHOI_PHUC: "THUNG_RAC_KHOI_PHUC",
  THUNG_RAC_XOA_VINH_VIEN: "THUNG_RAC_XOA_VINH_VIEN",
  // Xuất file.
  XUAT_FILE: "XUAT_FILE",
  // Sao lưu / phục hồi (route `/api/backup`, `/api/restore` — không phải server action nên không có
  // dòng trong `ANH_XA_ACTION_HANH_DONG`).
  SAO_LUU_TAI: "SAO_LUU_TAI",
  PHUC_HOI: "PHUC_HOI",
} as const;

export type HanhDong = (typeof HANH_DONG)[keyof typeof HANH_DONG];

/**
 * Server action (tên export) → mã nhật ký. Lưới tĩnh `tests/luoi/` đòi mọi action mutating có mặt
 * ở đây (hoặc trong allowlist không-nhật-ký của lưới). Phase thêm action thì thêm dòng tương ứng.
 */
export const ANH_XA_ACTION_HANH_DONG: Record<string, HanhDong> = {
  login: HANH_DONG.DANG_NHAP_OK,
  logout: HANH_DONG.DANG_XUAT,
  changePassword: HANH_DONG.DOI_MAT_KHAU,
  // Quản lý tài khoản (`actions/tai-khoan.ts`) + đổi mật khẩu lần đầu (`actions/doi-mat-khau-lan-dau.ts`).
  taoTaiKhoan: HANH_DONG.TAI_KHOAN_TAO,
  suaQuyenTaiKhoan: HANH_DONG.TAI_KHOAN_SUA_QUYEN,
  khoaTaiKhoan: HANH_DONG.TAI_KHOAN_KHOA,
  moKhoaTaiKhoan: HANH_DONG.TAI_KHOAN_MO_KHOA,
  xoaTaiKhoan: HANH_DONG.TAI_KHOAN_XOA,
  datLaiMatKhau: HANH_DONG.TAI_KHOAN_DAT_LAI_MK,
  doiMatKhauLanDau: HANH_DONG.DOI_MAT_KHAU_LAN_DAU,
  // Cài đặt, dữ liệu, đồng bộ, giá vốn, quảng cáo.
  deleteAllData: HANH_DONG.DU_LIEU_XOA_TOAN_BO,
  dungLaiTuKhoTho: HANH_DONG.DU_LIEU_DUNG_LAI_TU_KHO,
  updateChannels: HANH_DONG.CAI_DAT_KENH,
  recomputeFeesInRange: HANH_DONG.CAI_DAT_TINH_LAI_PHI,
  createExpenseCategory: HANH_DONG.DANH_MUC_CHI_PHI_TAO,
  renameExpenseCategory: HANH_DONG.DANH_MUC_CHI_PHI_SUA,
  toggleExpenseCategoryHidden: HANH_DONG.DANH_MUC_CHI_PHI_AN_HIEN,
  deleteExpenseCategory: HANH_DONG.DANH_MUC_CHI_PHI_XOA,
  updateDefaultLowStockThreshold: HANH_DONG.CAI_DAT_NGUONG_TON,
  updateShopInfo: HANH_DONG.CAI_DAT_THONG_TIN_SHOP,
  luuKhoaKetNoi: HANH_DONG.KHOA_KET_NOI_LUU,
  doiVaLuuTokenMeta: HANH_DONG.KHOA_KET_NOI_THAY_META,
  luuKetNoiN8n: HANH_DONG.N8N_LUU_KET_NOI,
  caiWorkflowsN8n: HANH_DONG.N8N_CAI_WORKFLOWS,
  triggerSyncNow: HANH_DONG.DONG_BO_KICH_HOAT,
  updateVariantThreshold: HANH_DONG.NGUONG_TON_SUA,
  updateProductThreshold: HANH_DONG.NGUONG_TON_SUA,
  updateVariantCost: HANH_DONG.GIA_VON_SUA,
  updateProductCost: HANH_DONG.GIA_VON_SUA,
  importCostPrices: HANH_DONG.GIA_VON_IMPORT,
  apGiaVonTheoPancake: HANH_DONG.GIA_VON_AP_THEO_PANCAKE,
  importAdsExpenses: HANH_DONG.ADS_IMPORT,
  // Tiền: dòng tiền, sổ quỹ, khoản vay, tiết kiệm, chi phí, thùng rác.
  createCashMovement: HANH_DONG.DONG_TIEN_TAO,
  updateCashMovement: HANH_DONG.DONG_TIEN_SUA,
  deleteCashMovement: HANH_DONG.DONG_TIEN_XOA,
  luuSoDuChotThang: HANH_DONG.CHOT_SO_DU_LUU,
  xoaSoDuChotThang: HANH_DONG.CHOT_SO_DU_XOA,
  importShopeeWallet: HANH_DONG.VI_SHOPEE_IMPORT,
  datQuyToiThieu: HANH_DONG.QUY_TOI_THIEU_DAT,
  taoKhoanVay: HANH_DONG.VAY_TAO,
  suaKhoanVay: HANH_DONG.VAY_SUA,
  xoaKhoanVay: HANH_DONG.VAY_XOA,
  tatToanKhoanVay: HANH_DONG.VAY_TAT_TOAN,
  ghiKyTraNo: HANH_DONG.VAY_GHI_KY,
  tatToanThauChi: HANH_DONG.THAU_CHI_TAT_TOAN,
  taoSoTietKiem: HANH_DONG.TIET_KIEM_TAO,
  suaSoTietKiem: HANH_DONG.TIET_KIEM_SUA,
  xoaSoTietKiem: HANH_DONG.TIET_KIEM_XOA,
  tatToanSoTietKiem: HANH_DONG.TIET_KIEM_TAT_TOAN,
  moLaiSoTietKiem: HANH_DONG.TIET_KIEM_MO_LAI,
  createExpense: HANH_DONG.CHI_PHI_TAO,
  updateExpense: HANH_DONG.CHI_PHI_SUA,
  deleteExpense: HANH_DONG.CHI_PHI_XOA,
  batLaiDinhKy: HANH_DONG.CHI_PHI_BAT_DINH_KY,
  stopRecurring: HANH_DONG.CHI_PHI_DUNG_DINH_KY,
  ghiChiPhiNhapHang: HANH_DONG.NHAP_HANG_GHI_CHI_PHI,
  khoiPhucBanGhi: HANH_DONG.THUNG_RAC_KHOI_PHUC,
  xoaVinhVienBanGhi: HANH_DONG.THUNG_RAC_XOA_VINH_VIEN,
};
